# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aogaki/DAQ/CAENDigitizer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aogaki/DAQ/CAENDigitizer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aogaki/DAQ/CAENDigitizer/CMakeFiles /home/aogaki/DAQ/CAENDigitizer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aogaki/DAQ/CAENDigitizer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named digi

# Build rule for target.
digi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 digi
.PHONY : digi

# fast build rule for target.
digi/fast:
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/build
.PHONY : digi/fast

#=============================================================================
# Target rules for targets named dpp

# Build rule for target.
dpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dpp
.PHONY : dpp

# fast build rule for target.
dpp/fast:
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/build
.PHONY : dpp/fast

dpp.o: dpp.cpp.o

.PHONY : dpp.o

# target to build an object file
dpp.cpp.o:
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/dpp.cpp.o
.PHONY : dpp.cpp.o

dpp.i: dpp.cpp.i

.PHONY : dpp.i

# target to preprocess a source file
dpp.cpp.i:
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/dpp.cpp.i
.PHONY : dpp.cpp.i

dpp.s: dpp.cpp.s

.PHONY : dpp.s

# target to generate assembly for a file
dpp.cpp.s:
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/dpp.cpp.s
.PHONY : dpp.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/main.cpp.s
.PHONY : main.cpp.s

src/TDPP.o: src/TDPP.cpp.o

.PHONY : src/TDPP.o

# target to build an object file
src/TDPP.cpp.o:
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TDPP.cpp.o
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TDPP.cpp.o
.PHONY : src/TDPP.cpp.o

src/TDPP.i: src/TDPP.cpp.i

.PHONY : src/TDPP.i

# target to preprocess a source file
src/TDPP.cpp.i:
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TDPP.cpp.i
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TDPP.cpp.i
.PHONY : src/TDPP.cpp.i

src/TDPP.s: src/TDPP.cpp.s

.PHONY : src/TDPP.s

# target to generate assembly for a file
src/TDPP.cpp.s:
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TDPP.cpp.s
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TDPP.cpp.s
.PHONY : src/TDPP.cpp.s

src/TDigitizer.o: src/TDigitizer.cpp.o

.PHONY : src/TDigitizer.o

# target to build an object file
src/TDigitizer.cpp.o:
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TDigitizer.cpp.o
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TDigitizer.cpp.o
.PHONY : src/TDigitizer.cpp.o

src/TDigitizer.i: src/TDigitizer.cpp.i

.PHONY : src/TDigitizer.i

# target to preprocess a source file
src/TDigitizer.cpp.i:
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TDigitizer.cpp.i
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TDigitizer.cpp.i
.PHONY : src/TDigitizer.cpp.i

src/TDigitizer.s: src/TDigitizer.cpp.s

.PHONY : src/TDigitizer.s

# target to generate assembly for a file
src/TDigitizer.cpp.s:
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TDigitizer.cpp.s
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TDigitizer.cpp.s
.PHONY : src/TDigitizer.cpp.s

src/TDigitizerCommand.o: src/TDigitizerCommand.cpp.o

.PHONY : src/TDigitizerCommand.o

# target to build an object file
src/TDigitizerCommand.cpp.o:
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TDigitizerCommand.cpp.o
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TDigitizerCommand.cpp.o
.PHONY : src/TDigitizerCommand.cpp.o

src/TDigitizerCommand.i: src/TDigitizerCommand.cpp.i

.PHONY : src/TDigitizerCommand.i

# target to preprocess a source file
src/TDigitizerCommand.cpp.i:
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TDigitizerCommand.cpp.i
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TDigitizerCommand.cpp.i
.PHONY : src/TDigitizerCommand.cpp.i

src/TDigitizerCommand.s: src/TDigitizerCommand.cpp.s

.PHONY : src/TDigitizerCommand.s

# target to generate assembly for a file
src/TDigitizerCommand.cpp.s:
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TDigitizerCommand.cpp.s
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TDigitizerCommand.cpp.s
.PHONY : src/TDigitizerCommand.cpp.s

src/TEveConverter.o: src/TEveConverter.cpp.o

.PHONY : src/TEveConverter.o

# target to build an object file
src/TEveConverter.cpp.o:
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TEveConverter.cpp.o
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TEveConverter.cpp.o
.PHONY : src/TEveConverter.cpp.o

src/TEveConverter.i: src/TEveConverter.cpp.i

.PHONY : src/TEveConverter.i

# target to preprocess a source file
src/TEveConverter.cpp.i:
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TEveConverter.cpp.i
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TEveConverter.cpp.i
.PHONY : src/TEveConverter.cpp.i

src/TEveConverter.s: src/TEveConverter.cpp.s

.PHONY : src/TEveConverter.s

# target to generate assembly for a file
src/TEveConverter.cpp.s:
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TEveConverter.cpp.s
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TEveConverter.cpp.s
.PHONY : src/TEveConverter.cpp.s

src/TTestDigi.o: src/TTestDigi.cpp.o

.PHONY : src/TTestDigi.o

# target to build an object file
src/TTestDigi.cpp.o:
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TTestDigi.cpp.o
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TTestDigi.cpp.o
.PHONY : src/TTestDigi.cpp.o

src/TTestDigi.i: src/TTestDigi.cpp.i

.PHONY : src/TTestDigi.i

# target to preprocess a source file
src/TTestDigi.cpp.i:
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TTestDigi.cpp.i
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TTestDigi.cpp.i
.PHONY : src/TTestDigi.cpp.i

src/TTestDigi.s: src/TTestDigi.cpp.s

.PHONY : src/TTestDigi.s

# target to generate assembly for a file
src/TTestDigi.cpp.s:
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TTestDigi.cpp.s
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TTestDigi.cpp.s
.PHONY : src/TTestDigi.cpp.s

src/TWaveRecord.o: src/TWaveRecord.cpp.o

.PHONY : src/TWaveRecord.o

# target to build an object file
src/TWaveRecord.cpp.o:
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TWaveRecord.cpp.o
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TWaveRecord.cpp.o
.PHONY : src/TWaveRecord.cpp.o

src/TWaveRecord.i: src/TWaveRecord.cpp.i

.PHONY : src/TWaveRecord.i

# target to preprocess a source file
src/TWaveRecord.cpp.i:
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TWaveRecord.cpp.i
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TWaveRecord.cpp.i
.PHONY : src/TWaveRecord.cpp.i

src/TWaveRecord.s: src/TWaveRecord.cpp.s

.PHONY : src/TWaveRecord.s

# target to generate assembly for a file
src/TWaveRecord.cpp.s:
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TWaveRecord.cpp.s
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TWaveRecord.cpp.s
.PHONY : src/TWaveRecord.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... digi"
	@echo "... edit_cache"
	@echo "... dpp"
	@echo "... dpp.o"
	@echo "... dpp.i"
	@echo "... dpp.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/TDPP.o"
	@echo "... src/TDPP.i"
	@echo "... src/TDPP.s"
	@echo "... src/TDigitizer.o"
	@echo "... src/TDigitizer.i"
	@echo "... src/TDigitizer.s"
	@echo "... src/TDigitizerCommand.o"
	@echo "... src/TDigitizerCommand.i"
	@echo "... src/TDigitizerCommand.s"
	@echo "... src/TEveConverter.o"
	@echo "... src/TEveConverter.i"
	@echo "... src/TEveConverter.s"
	@echo "... src/TTestDigi.o"
	@echo "... src/TTestDigi.i"
	@echo "... src/TTestDigi.s"
	@echo "... src/TWaveRecord.o"
	@echo "... src/TWaveRecord.i"
	@echo "... src/TWaveRecord.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

