# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aogaki/DAQ/CAENDigitizer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aogaki/DAQ/CAENDigitizer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aogaki/DAQ/CAENDigitizer/CMakeFiles /home/aogaki/DAQ/CAENDigitizer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aogaki/DAQ/CAENDigitizer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sync

# Build rule for target.
sync: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sync
.PHONY : sync

# fast build rule for target.
sync/fast:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/build
.PHONY : sync/fast

#=============================================================================
# Target rules for targets named PHA

# Build rule for target.
PHA: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PHA
.PHONY : PHA

# fast build rule for target.
PHA/fast:
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/build
.PHONY : PHA/fast

#=============================================================================
# Target rules for targets named dpp

# Build rule for target.
dpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dpp
.PHONY : dpp

# fast build rule for target.
dpp/fast:
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/build
.PHONY : dpp/fast

#=============================================================================
# Target rules for targets named digi

# Build rule for target.
digi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 digi
.PHONY : digi

# fast build rule for target.
digi/fast:
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/build
.PHONY : digi/fast

PHA.o: PHA.cpp.o

.PHONY : PHA.o

# target to build an object file
PHA.cpp.o:
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/PHA.cpp.o
.PHONY : PHA.cpp.o

PHA.i: PHA.cpp.i

.PHONY : PHA.i

# target to preprocess a source file
PHA.cpp.i:
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/PHA.cpp.i
.PHONY : PHA.cpp.i

PHA.s: PHA.cpp.s

.PHONY : PHA.s

# target to generate assembly for a file
PHA.cpp.s:
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/PHA.cpp.s
.PHONY : PHA.cpp.s

dpp.o: dpp.cpp.o

.PHONY : dpp.o

# target to build an object file
dpp.cpp.o:
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/dpp.cpp.o
.PHONY : dpp.cpp.o

dpp.i: dpp.cpp.i

.PHONY : dpp.i

# target to preprocess a source file
dpp.cpp.i:
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/dpp.cpp.i
.PHONY : dpp.cpp.i

dpp.s: dpp.cpp.s

.PHONY : dpp.s

# target to generate assembly for a file
dpp.cpp.s:
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/dpp.cpp.s
.PHONY : dpp.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/main.cpp.s
.PHONY : main.cpp.s

src/MyFunctions.o: src/MyFunctions.cpp.o

.PHONY : src/MyFunctions.o

# target to build an object file
src/MyFunctions.cpp.o:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/src/MyFunctions.cpp.o
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/src/MyFunctions.cpp.o
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/MyFunctions.cpp.o
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/MyFunctions.cpp.o
.PHONY : src/MyFunctions.cpp.o

src/MyFunctions.i: src/MyFunctions.cpp.i

.PHONY : src/MyFunctions.i

# target to preprocess a source file
src/MyFunctions.cpp.i:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/src/MyFunctions.cpp.i
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/src/MyFunctions.cpp.i
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/MyFunctions.cpp.i
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/MyFunctions.cpp.i
.PHONY : src/MyFunctions.cpp.i

src/MyFunctions.s: src/MyFunctions.cpp.s

.PHONY : src/MyFunctions.s

# target to generate assembly for a file
src/MyFunctions.cpp.s:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/src/MyFunctions.cpp.s
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/src/MyFunctions.cpp.s
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/MyFunctions.cpp.s
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/MyFunctions.cpp.s
.PHONY : src/MyFunctions.cpp.s

src/TDPP.o: src/TDPP.cpp.o

.PHONY : src/TDPP.o

# target to build an object file
src/TDPP.cpp.o:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/src/TDPP.cpp.o
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/src/TDPP.cpp.o
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TDPP.cpp.o
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TDPP.cpp.o
.PHONY : src/TDPP.cpp.o

src/TDPP.i: src/TDPP.cpp.i

.PHONY : src/TDPP.i

# target to preprocess a source file
src/TDPP.cpp.i:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/src/TDPP.cpp.i
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/src/TDPP.cpp.i
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TDPP.cpp.i
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TDPP.cpp.i
.PHONY : src/TDPP.cpp.i

src/TDPP.s: src/TDPP.cpp.s

.PHONY : src/TDPP.s

# target to generate assembly for a file
src/TDPP.cpp.s:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/src/TDPP.cpp.s
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/src/TDPP.cpp.s
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TDPP.cpp.s
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TDPP.cpp.s
.PHONY : src/TDPP.cpp.s

src/TDigiPHA.o: src/TDigiPHA.cpp.o

.PHONY : src/TDigiPHA.o

# target to build an object file
src/TDigiPHA.cpp.o:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/src/TDigiPHA.cpp.o
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/src/TDigiPHA.cpp.o
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TDigiPHA.cpp.o
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TDigiPHA.cpp.o
.PHONY : src/TDigiPHA.cpp.o

src/TDigiPHA.i: src/TDigiPHA.cpp.i

.PHONY : src/TDigiPHA.i

# target to preprocess a source file
src/TDigiPHA.cpp.i:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/src/TDigiPHA.cpp.i
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/src/TDigiPHA.cpp.i
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TDigiPHA.cpp.i
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TDigiPHA.cpp.i
.PHONY : src/TDigiPHA.cpp.i

src/TDigiPHA.s: src/TDigiPHA.cpp.s

.PHONY : src/TDigiPHA.s

# target to generate assembly for a file
src/TDigiPHA.cpp.s:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/src/TDigiPHA.cpp.s
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/src/TDigiPHA.cpp.s
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TDigiPHA.cpp.s
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TDigiPHA.cpp.s
.PHONY : src/TDigiPHA.cpp.s

src/TDigiPar.o: src/TDigiPar.cpp.o

.PHONY : src/TDigiPar.o

# target to build an object file
src/TDigiPar.cpp.o:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/src/TDigiPar.cpp.o
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/src/TDigiPar.cpp.o
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TDigiPar.cpp.o
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TDigiPar.cpp.o
.PHONY : src/TDigiPar.cpp.o

src/TDigiPar.i: src/TDigiPar.cpp.i

.PHONY : src/TDigiPar.i

# target to preprocess a source file
src/TDigiPar.cpp.i:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/src/TDigiPar.cpp.i
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/src/TDigiPar.cpp.i
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TDigiPar.cpp.i
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TDigiPar.cpp.i
.PHONY : src/TDigiPar.cpp.i

src/TDigiPar.s: src/TDigiPar.cpp.s

.PHONY : src/TDigiPar.s

# target to generate assembly for a file
src/TDigiPar.cpp.s:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/src/TDigiPar.cpp.s
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/src/TDigiPar.cpp.s
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TDigiPar.cpp.s
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TDigiPar.cpp.s
.PHONY : src/TDigiPar.cpp.s

src/TDigitizer.o: src/TDigitizer.cpp.o

.PHONY : src/TDigitizer.o

# target to build an object file
src/TDigitizer.cpp.o:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/src/TDigitizer.cpp.o
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/src/TDigitizer.cpp.o
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TDigitizer.cpp.o
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TDigitizer.cpp.o
.PHONY : src/TDigitizer.cpp.o

src/TDigitizer.i: src/TDigitizer.cpp.i

.PHONY : src/TDigitizer.i

# target to preprocess a source file
src/TDigitizer.cpp.i:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/src/TDigitizer.cpp.i
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/src/TDigitizer.cpp.i
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TDigitizer.cpp.i
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TDigitizer.cpp.i
.PHONY : src/TDigitizer.cpp.i

src/TDigitizer.s: src/TDigitizer.cpp.s

.PHONY : src/TDigitizer.s

# target to generate assembly for a file
src/TDigitizer.cpp.s:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/src/TDigitizer.cpp.s
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/src/TDigitizer.cpp.s
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TDigitizer.cpp.s
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TDigitizer.cpp.s
.PHONY : src/TDigitizer.cpp.s

src/TDigitizerCommand.o: src/TDigitizerCommand.cpp.o

.PHONY : src/TDigitizerCommand.o

# target to build an object file
src/TDigitizerCommand.cpp.o:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/src/TDigitizerCommand.cpp.o
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/src/TDigitizerCommand.cpp.o
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TDigitizerCommand.cpp.o
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TDigitizerCommand.cpp.o
.PHONY : src/TDigitizerCommand.cpp.o

src/TDigitizerCommand.i: src/TDigitizerCommand.cpp.i

.PHONY : src/TDigitizerCommand.i

# target to preprocess a source file
src/TDigitizerCommand.cpp.i:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/src/TDigitizerCommand.cpp.i
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/src/TDigitizerCommand.cpp.i
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TDigitizerCommand.cpp.i
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TDigitizerCommand.cpp.i
.PHONY : src/TDigitizerCommand.cpp.i

src/TDigitizerCommand.s: src/TDigitizerCommand.cpp.s

.PHONY : src/TDigitizerCommand.s

# target to generate assembly for a file
src/TDigitizerCommand.cpp.s:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/src/TDigitizerCommand.cpp.s
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/src/TDigitizerCommand.cpp.s
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TDigitizerCommand.cpp.s
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TDigitizerCommand.cpp.s
.PHONY : src/TDigitizerCommand.cpp.s

src/TEveConverter.o: src/TEveConverter.cpp.o

.PHONY : src/TEveConverter.o

# target to build an object file
src/TEveConverter.cpp.o:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/src/TEveConverter.cpp.o
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/src/TEveConverter.cpp.o
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TEveConverter.cpp.o
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TEveConverter.cpp.o
.PHONY : src/TEveConverter.cpp.o

src/TEveConverter.i: src/TEveConverter.cpp.i

.PHONY : src/TEveConverter.i

# target to preprocess a source file
src/TEveConverter.cpp.i:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/src/TEveConverter.cpp.i
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/src/TEveConverter.cpp.i
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TEveConverter.cpp.i
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TEveConverter.cpp.i
.PHONY : src/TEveConverter.cpp.i

src/TEveConverter.s: src/TEveConverter.cpp.s

.PHONY : src/TEveConverter.s

# target to generate assembly for a file
src/TEveConverter.cpp.s:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/src/TEveConverter.cpp.s
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/src/TEveConverter.cpp.s
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TEveConverter.cpp.s
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TEveConverter.cpp.s
.PHONY : src/TEveConverter.cpp.s

src/TPHA.o: src/TPHA.cpp.o

.PHONY : src/TPHA.o

# target to build an object file
src/TPHA.cpp.o:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/src/TPHA.cpp.o
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/src/TPHA.cpp.o
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TPHA.cpp.o
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TPHA.cpp.o
.PHONY : src/TPHA.cpp.o

src/TPHA.i: src/TPHA.cpp.i

.PHONY : src/TPHA.i

# target to preprocess a source file
src/TPHA.cpp.i:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/src/TPHA.cpp.i
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/src/TPHA.cpp.i
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TPHA.cpp.i
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TPHA.cpp.i
.PHONY : src/TPHA.cpp.i

src/TPHA.s: src/TPHA.cpp.s

.PHONY : src/TPHA.s

# target to generate assembly for a file
src/TPHA.cpp.s:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/src/TPHA.cpp.s
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/src/TPHA.cpp.s
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TPHA.cpp.s
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TPHA.cpp.s
.PHONY : src/TPHA.cpp.s

src/TPSD.o: src/TPSD.cpp.o

.PHONY : src/TPSD.o

# target to build an object file
src/TPSD.cpp.o:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/src/TPSD.cpp.o
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/src/TPSD.cpp.o
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TPSD.cpp.o
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TPSD.cpp.o
.PHONY : src/TPSD.cpp.o

src/TPSD.i: src/TPSD.cpp.i

.PHONY : src/TPSD.i

# target to preprocess a source file
src/TPSD.cpp.i:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/src/TPSD.cpp.i
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/src/TPSD.cpp.i
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TPSD.cpp.i
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TPSD.cpp.i
.PHONY : src/TPSD.cpp.i

src/TPSD.s: src/TPSD.cpp.s

.PHONY : src/TPSD.s

# target to generate assembly for a file
src/TPSD.cpp.s:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/src/TPSD.cpp.s
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/src/TPSD.cpp.s
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TPSD.cpp.s
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TPSD.cpp.s
.PHONY : src/TPSD.cpp.s

src/TParameters.o: src/TParameters.cpp.o

.PHONY : src/TParameters.o

# target to build an object file
src/TParameters.cpp.o:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/src/TParameters.cpp.o
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/src/TParameters.cpp.o
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TParameters.cpp.o
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TParameters.cpp.o
.PHONY : src/TParameters.cpp.o

src/TParameters.i: src/TParameters.cpp.i

.PHONY : src/TParameters.i

# target to preprocess a source file
src/TParameters.cpp.i:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/src/TParameters.cpp.i
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/src/TParameters.cpp.i
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TParameters.cpp.i
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TParameters.cpp.i
.PHONY : src/TParameters.cpp.i

src/TParameters.s: src/TParameters.cpp.s

.PHONY : src/TParameters.s

# target to generate assembly for a file
src/TParameters.cpp.s:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/src/TParameters.cpp.s
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/src/TParameters.cpp.s
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TParameters.cpp.s
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TParameters.cpp.s
.PHONY : src/TParameters.cpp.s

src/TTestDigi.o: src/TTestDigi.cpp.o

.PHONY : src/TTestDigi.o

# target to build an object file
src/TTestDigi.cpp.o:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/src/TTestDigi.cpp.o
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/src/TTestDigi.cpp.o
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TTestDigi.cpp.o
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TTestDigi.cpp.o
.PHONY : src/TTestDigi.cpp.o

src/TTestDigi.i: src/TTestDigi.cpp.i

.PHONY : src/TTestDigi.i

# target to preprocess a source file
src/TTestDigi.cpp.i:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/src/TTestDigi.cpp.i
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/src/TTestDigi.cpp.i
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TTestDigi.cpp.i
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TTestDigi.cpp.i
.PHONY : src/TTestDigi.cpp.i

src/TTestDigi.s: src/TTestDigi.cpp.s

.PHONY : src/TTestDigi.s

# target to generate assembly for a file
src/TTestDigi.cpp.s:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/src/TTestDigi.cpp.s
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/src/TTestDigi.cpp.s
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TTestDigi.cpp.s
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TTestDigi.cpp.s
.PHONY : src/TTestDigi.cpp.s

src/TWaveRecord.o: src/TWaveRecord.cpp.o

.PHONY : src/TWaveRecord.o

# target to build an object file
src/TWaveRecord.cpp.o:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/src/TWaveRecord.cpp.o
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/src/TWaveRecord.cpp.o
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TWaveRecord.cpp.o
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TWaveRecord.cpp.o
.PHONY : src/TWaveRecord.cpp.o

src/TWaveRecord.i: src/TWaveRecord.cpp.i

.PHONY : src/TWaveRecord.i

# target to preprocess a source file
src/TWaveRecord.cpp.i:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/src/TWaveRecord.cpp.i
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/src/TWaveRecord.cpp.i
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TWaveRecord.cpp.i
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TWaveRecord.cpp.i
.PHONY : src/TWaveRecord.cpp.i

src/TWaveRecord.s: src/TWaveRecord.cpp.s

.PHONY : src/TWaveRecord.s

# target to generate assembly for a file
src/TWaveRecord.cpp.s:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/src/TWaveRecord.cpp.s
	$(MAKE) -f CMakeFiles/PHA.dir/build.make CMakeFiles/PHA.dir/src/TWaveRecord.cpp.s
	$(MAKE) -f CMakeFiles/dpp.dir/build.make CMakeFiles/dpp.dir/src/TWaveRecord.cpp.s
	$(MAKE) -f CMakeFiles/digi.dir/build.make CMakeFiles/digi.dir/src/TWaveRecord.cpp.s
.PHONY : src/TWaveRecord.cpp.s

sync.o: sync.cpp.o

.PHONY : sync.o

# target to build an object file
sync.cpp.o:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/sync.cpp.o
.PHONY : sync.cpp.o

sync.i: sync.cpp.i

.PHONY : sync.i

# target to preprocess a source file
sync.cpp.i:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/sync.cpp.i
.PHONY : sync.cpp.i

sync.s: sync.cpp.s

.PHONY : sync.s

# target to generate assembly for a file
sync.cpp.s:
	$(MAKE) -f CMakeFiles/sync.dir/build.make CMakeFiles/sync.dir/sync.cpp.s
.PHONY : sync.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... sync"
	@echo "... PHA"
	@echo "... dpp"
	@echo "... edit_cache"
	@echo "... digi"
	@echo "... PHA.o"
	@echo "... PHA.i"
	@echo "... PHA.s"
	@echo "... dpp.o"
	@echo "... dpp.i"
	@echo "... dpp.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/MyFunctions.o"
	@echo "... src/MyFunctions.i"
	@echo "... src/MyFunctions.s"
	@echo "... src/TDPP.o"
	@echo "... src/TDPP.i"
	@echo "... src/TDPP.s"
	@echo "... src/TDigiPHA.o"
	@echo "... src/TDigiPHA.i"
	@echo "... src/TDigiPHA.s"
	@echo "... src/TDigiPar.o"
	@echo "... src/TDigiPar.i"
	@echo "... src/TDigiPar.s"
	@echo "... src/TDigitizer.o"
	@echo "... src/TDigitizer.i"
	@echo "... src/TDigitizer.s"
	@echo "... src/TDigitizerCommand.o"
	@echo "... src/TDigitizerCommand.i"
	@echo "... src/TDigitizerCommand.s"
	@echo "... src/TEveConverter.o"
	@echo "... src/TEveConverter.i"
	@echo "... src/TEveConverter.s"
	@echo "... src/TPHA.o"
	@echo "... src/TPHA.i"
	@echo "... src/TPHA.s"
	@echo "... src/TPSD.o"
	@echo "... src/TPSD.i"
	@echo "... src/TPSD.s"
	@echo "... src/TParameters.o"
	@echo "... src/TParameters.i"
	@echo "... src/TParameters.s"
	@echo "... src/TTestDigi.o"
	@echo "... src/TTestDigi.i"
	@echo "... src/TTestDigi.s"
	@echo "... src/TWaveRecord.o"
	@echo "... src/TWaveRecord.i"
	@echo "... src/TWaveRecord.s"
	@echo "... sync.o"
	@echo "... sync.i"
	@echo "... sync.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

