COMP_NAME = SampleReader

all: $(COMP_NAME)Comp

SRCS += TDigitizer.cpp
SRCS += $(COMP_NAME).cpp
SRCS += $(COMP_NAME)Comp.cpp

LDFLAGS  += -L/usr/lib/daqmw
LDLIBS += -lSock
LDLIBS += -lCAENDigitizer
CPPFLAGS += -I$(shell root-config --incdir)
LDFLAGS += $(shell root-config --glibs)

# sample install target
#
# MODE = 0755
# BINDIR = /tmp/mybinary
#
# install: $(COMP_NAME)Comp
#	mkdir -p $(BINDIR)
#	install -m $(MODE) $(COMP_NAME)Comp $(BINDIR)

include /usr/share/daqmw/mk/comp.mk
