# -*- Makefile -*-
#
# @file  Makefile
# @brief makefile for DaqComponents
# @date  $Date: 2009/06/12 10:42:55 $
#

all:
	make -f Makefile.Reader
	make -f Makefile.Dispatcher
	make -f Makefile.Logger
	make -f Makefile.Monitor

clean:
	make -f Makefile.Reader clean
	make -f Makefile.Dispatcher clean
	make -f Makefile.Logger clean
	make -f Makefile.Monitor clean
