# -*- Makefile -*-
#
# @file  Makefile
# @brief makefile for DaqComponents
# @date  $Date: 2009/06/12 10:42:55 $
#

all:
	make -C TinySink
	make -C TinySource

clean:
	make -C TinySink clean
	make -C TinySource clean
